stages:
  - build
  - deploy
  - release

.build:
  image: zephyrprojectrtos/zephyr-build:v0.26.13
  before_script:
    - sudo apt-get update && sudo apt-get install -y jq
    - rm -rf ../.west
    - west init -l --mf west_${CI_JOB_NAME}.yml .
    - west update
    - ln -srf ../modules/lib/ArduinoCore-API/api ../modules/lib/Arduino-Zephyr-API/cores/arduino/.
    - west zephyr-export
    - pip3 install -r ../zephyr/scripts/requirements-base.txt
  script:
    - source ../zephyr/zephyr-env.sh
    - west build -b beagleconnect_freedom . -p
  after_script:
    - VM=$(cat ../modules/microblocks/gp/runtime/versions | grep VM | awk '{print $2}')
    - mkdir -p release/microblocks/${VM}-${CI_JOB_NAME}/
    - file=release/microblocks/${VM}-${CI_JOB_NAME}/microblocks-${VM}-${CI_JOB_NAME}.bin.xz
    - xz -vc build/zephyr/zephyr.bin > $file
    - export name="MicroBlocks ${CI_JOB_NAME}"
    - export description="MicroBlocks is a blocks programming language for physical computing inspired by Scratch."
    - export icon="https://microblocks.fun/assets/img/logos/MicroBlocks-white.svg"
    - jq -n '.name = env.name | .description = env.description | .icon = env.icon | .devices = ["beagleconnect-freedom"] | .tags = ["education"]' > $file.bb.imager.json
  artifacts:
    paths:
      - release/

dev:
  stage: build
  extends: .build

pilot:
  stage: build
  extends: .build

stable:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
  extends: .build

include:
  - component: openbeagle.org/ayush1325/ci-components/package-registry-upload@81dd0fe220b9362f19f41cbca4d60d119536efaa
    rules:
      - if: $CI_DEFAULT_BRANCH == $CI_COMMIT_BRANCH
    inputs:
      job-name: deploy-testing-job
      job-needs: ["dev", "pilot"]
      job-stage: deploy
      release_dir: ${CI_PROJECT_DIR}/release
  - component: openbeagle.org/ayush1325/ci-components/package-registry-upload@81dd0fe220b9362f19f41cbca4d60d119536efaa
    rules:
      - if: $CI_COMMIT_TAG
    inputs:
      job-name: deploy-stable-job
      job-needs: ["stable"]
      job-stage: deploy
      release_dir: ${CI_PROJECT_DIR}/release
  - component: openbeagle.org/ayush1325/ci-components/os-list@81dd0fe220b9362f19f41cbca4d60d119536efaa
    rules:
      - if: $CI_DEFAULT_BRANCH == $CI_COMMIT_BRANCH
    inputs:
      job-name: os-list-testing-job
      job-needs: ["dev", "pilot"]
      job-stage: deploy
      release_dir: ${CI_PROJECT_DIR}/release
      os_list_url_suffix: "os_list/testing/os_list.json"
  - component: openbeagle.org/ayush1325/ci-components/os-list@81dd0fe220b9362f19f41cbca4d60d119536efaa
    rules:
      - if: $CI_COMMIT_TAG
    inputs:
      job-name: os-list-stable-job
      job-needs: ["stable"]
      job-stage: deploy
      release_dir: ${CI_PROJECT_DIR}/release
      os_list_template: scripts/os_list.json
      os_list_url_suffix: "os_list/stable/os_list.json"
  - component: openbeagle.org/ayush1325/ci-components/release-from-file@81dd0fe220b9362f19f41cbca4d60d119536efaa
    rules:
      - if: $CI_COMMIT_TAG
    inputs:
      job-name: release-stable-job
      job-needs: ["deploy-stable-job"]
      job-stage: release
      release_file: release/release.yml
