stages:
  - build
  - deploy

.build:
  script:
    - source ../zephyr/zephyr-env.sh
    - west build -b beagleconnect_freedom . -p

default:
  image: zephyrprojectrtos/zephyr-build:v0.26.13
  before_script:
    - rm -rf ../.west
    - west init -l --mf west_${CI_JOB_NAME}.yml .
    - west update
    - ln -srf ../modules/lib/ArduinoCore-API/api ../modules/lib/Arduino-Zephyr-API/cores/arduino/.
    - west zephyr-export
    - pip3 install -r ../zephyr/scripts/requirements-base.txt
  after_script:
    - mkdir ${CI_JOB_NAME}
    - cp ../modules/microblocks/gp/runtime/versions ${CI_JOB_NAME}/versions
    - xz -vc build/zephyr/zephyr.bin > ${CI_JOB_NAME}/microblocks.bin.xz
  artifacts:
    name: "microblocks-${CI_JOB_NAME}"
    paths:
      - ${CI_JOB_NAME}/*

dev:
  stage: build
  extends: .build

pilot:
  stage: build
  extends: .build

stable:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
  extends: .build

deploy:
  inherit:
    default: false
  stage: deploy
  image: curlimages/curl:latest
  script:
    - VM=$(cat dev/versions | grep VM | awk '{print $2}')
    - 'curl --fail-with-body --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file dev/microblocks.bin.xz ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/dev/${VM}/microblocks.bin.xz'
    - VM=$(cat pilot/versions | grep VM | awk '{print $2}')
    - 'curl --fail-with-body --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file pilot/microblocks.bin.xz ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/pilot/${VM}/microblocks.bin.xz'

release:
  inherit:
    default: false
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG
  before_script:
    - apk add --no-cache curl
  script:
    - echo "running release_job for $CI_COMMIT_TAG"
    - VM=$(cat stable/versions | grep VM | awk '{print $2}')
    - 'curl --fail-with-body --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file stable/microblocks.bin.xz ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/stable/${VM}/microblocks.bin.xz'
  release:
    tag_name: $CI_COMMIT_TAG
    name: 'MicroBlocks VM $CI_COMMIT_TAG'
    description: 'MicroBlocks VM $CI_COMMIT_TAG stable firmware'
    assets:
      links:
        - name: 'MicroBlocks Firmware for BeagleConnect Freedom'
          url: '${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/stable/${CI_COMMIT_TAG}/microblocks.bin.xz'
          link_type: 'package'
