stages:
  - build
  - deploy
  - release

.build:
  image: zephyrprojectrtos/zephyr-build:v0.26.13
  before_script:
    - rm -rf ../.west
    - west init -l --mf west_${CI_JOB_NAME}.yml .
    - west update
    - ln -srf ../modules/lib/ArduinoCore-API/api ../modules/lib/Arduino-Zephyr-API/cores/arduino/.
    - west zephyr-export
    - pip3 install -r ../zephyr/scripts/requirements-base.txt
  script:
    - source ../zephyr/zephyr-env.sh
    - west build -b beagleconnect_freedom . -p
  after_script:
    - VM=$(cat ../modules/microblocks/gp/runtime/versions | grep VM | awk '{print $2}')
    - mkdir -p release/microblocks/${VM}-${CI_JOB_NAME}/
    - xz -vc build/zephyr/zephyr.bin > release/microblocks/${VM}-${CI_JOB_NAME}/microblocks-${VM}-${CI_JOB_NAME}.bin.xz
  artifacts:
    paths:
      - release/

dev:
  stage: build
  extends: .build

pilot:
  stage: build
  extends: .build

stable:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
  extends: .build

include:
  - component: openbeagle.org/ayush1325/ci-components/package-registry-upload@59ea19d89c79a2516c96d3fd0a2ce5abf7a4cc2a
    rules:
      - if: $CI_DEFAULT_BRANCH == $CI_COMMIT_BRANCH
    inputs:
      job-name: deploy-testing-job
      job-needs: ["dev", "pilot"]
      job-stage: deploy
      release_dir: ${CI_PROJECT_DIR}/release
  - component: openbeagle.org/ayush1325/ci-components/package-registry-upload@59ea19d89c79a2516c96d3fd0a2ce5abf7a4cc2a
    rules:
      - if: $CI_COMMIT_TAG
    inputs:
      job-name: deploy-stable-job
      job-needs: ["stable"]
      job-stage: deploy
      release_dir: ${CI_PROJECT_DIR}/release
  - component: openbeagle.org/ayush1325/ci-components/release-from-file@59ea19d89c79a2516c96d3fd0a2ce5abf7a4cc2a
    rules:
      - if: $CI_COMMIT_TAG
    inputs:
      job-name: release-stable-job
      job-needs: ["deploy-stable-job"]
      job-stage: release
      release_file: release/release.yml
