default:
  image: zephyrprojectrtos/zephyr-build:v0.26.13
  before_script:
    - rm -rf ../.west
  after_script:
    - xz - v build/zephyr/zephyr.bin
  artifacts:
    paths:
      - build/zephyr/zephyr.bin.xz

build-dev:
  stage: build
  before_script:
    - west init -l .
    - west update
    - ln -srf ../modules/lib/ArduinoCore-API/api ../modules/lib/Arduino-Zephyr-API/cores/arduino/.
    - west zephyr-export
    - pip3 install -r ../zephyr/scripts/requirements-base.txt
  script:
    - source ../zephyr/zephyr-env.sh
    - west build -b beagleconnect_freedom . -p

build-pilot:
  stage: build
  before_script:
    - west init -l --mf west_pilot.yml .
    - west update
    - ln -srf ../modules/lib/ArduinoCore-API/api ../modules/lib/Arduino-Zephyr-API/cores/arduino/.
    - west zephyr-export
    - pip3 install -r ../zephyr/scripts/requirements-base.txt
  script:
    - source ../zephyr/zephyr-env.sh
    - west build -b beagleconnect_freedom . -p
